(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* This notebook creates the figures for the St. Louis Fed keynote speech. *)


(* Set up the environment in which the figure-generating files can be executed *)
ClearAll["Global`*"];ParamsAreSet=False;
If[$VersionNumber<8,(*then*) Print["These programs require Mathematica version 8 or greater."];Abort[]];
If[Length[$FrontEnd] > 0,NBDir=SetDirectory[NotebookDirectory[]]];(* If running from the Notebook interface *)
rootDir = SetDirectory["../../.."];
AutoLoadDir=SetDirectory["./Mathematica/CoreCode/Autoload"];Get["./init.m"];
CoreCodeDir=SetDirectory[".."];
rootDir = SetDirectory[".."];
Get[CoreCodeDir<>"/MakeAnalyticalResults.m"];
Get[CoreCodeDir<>"/VarsAndFuncs.m"];
(* Method of creating figures depends on whether being run in batch mode or interactively *)
If[$FrontEnd == Null,OpenFigsUsingShell=True,OpenFigsUsingShell=False]; 
Get[CoreCodeDir<>"/DrawDiagrams.m"];
FigsDir=SetDirectory[rootDir<>"/Examples/FedStLouis/Figures/"];
CodeDir=SetDirectory[rootDir<>"/Examples/FedStLouis"];
VerboseOutput=False;
PlotRangeVertical={-0.5,0.15};


(* We use the set of parameter values of ctDiscrete except that Severance = 4; we also incorporate death rate = 0.05.*)
Get[CoreCodeDir<>"/ParametersBase.m"];
(* We calculate the discount rates for patient and impatient people to match debt and asset ratios in 2001. *)
Severance = 4;
PDies = 0.05;
Get[CodeDir<>"/CalDiscRate.m"];
\[CurlyTheta]Impatient = CalDiscRate[-2];
\[CurlyTheta]Patient=CalDiscRate[12];


(* Plot saving dynamics over credit cycle. *)

Get[CodeDir<>"/SavPathOverECreditCycleSlow.m"];
Print[Show[SavPathOverECreditCycleSlow]];


(* Plot saving dynamics over credit cycle. *)

Get[CodeDir<>"/SavPathOverECreditCycle.m"];
Print[Show[SavPathOverECreditCycle]];


(* Plot Saving dynamics when there is a decrease in unemployment rate expectations then an abrupt reversal of expectation. *)
Get[CoreCodeDir<>"/ParametersBase.m"];
Severance =4;
PDies = 0.05;
Get[CodeDir<>"/CalDiscRate.m"];
\[CurlyTheta]Impatient = CalDiscRate[-2];
\[CurlyTheta]Patient=CalDiscRate[12];
Get[CodeDir<>"/SavPathOverEUriskCycle.m"];
Print[Show[SavPathOverEUriskCycle]];


(* Plot saving dynamics when there is an increase of growth expectation then an abrupt reversal of the expectation *)
Get[CoreCodeDir<>"/ParametersBase.m"];
Severance = 4;
PDies = 0.05;
Get[CodeDir<>"/SavPathOverEGrowthCycle.m"];
Print[Show[SavPathOverEGrowthCycle]];


Export[FigsDir<>"/SavPathOverECycles.pdf",SavPathOverECycles];



