(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(*
Note that even in regions were the relationship between \[Mho] and the target wealth-income ratio is negative, the relationship between \[Mho] and the SAVING RATE is positive; this is illustrated by the following figure.  The negative relationship between \[Mho] and the ratio reflects the fact that growth is adjusted upward as \[Mho] rises in order to keep the PDV of labor income constant; faster net growth (for the continuing-employed) means that it is harder to maintain a given ratio of wealth to income.
*)
Plot[(1+(\[ScriptM]E-1)((r)/(R))-\[ScriptC]E)/(1+(\[ScriptM]E-1)((r)/(R))),{\[Mho],0.001,0.10}]
