(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



SetDirectory[NotebookDirectory[]];<<ManipulatePrepare.m;FindStableArm;
{\[ScriptM]Max,\[ScriptM]MaxMax}={2,3} \[ScriptM]E;\[ScriptC]Max=cE[\[ScriptM]MaxMax];
Manipulate[
Block[{$PerformanceGoal="Quality", \[CurlyTheta]},\[CurlyTheta]=\[CurlyTheta]Base;
\[CurlyTheta]=\[CurlyTheta]Slider;If[((R) \[Beta])^(1/\[Rho])/\[CapitalGamma] >=  1||((R) \[Beta])^(1/\[Rho])/(R) >=  1,Style[Text["Impatience Condition Not Satisfied."],24];Abort[]];
DrawPhaseDiagram[\[ScriptM]Max,\[ScriptM]MaxMax,\[ScriptC]Max]
],{{\[CurlyTheta]Slider,.10,"\[CurlyTheta]"},.10-.025,.10+0.025,0.005}]
