(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ClearAll["Global`*"];
SetDirectory[NotebookDirectory[]];<<ManipulatePrepare.m;
FindStableArm;
{\[ScriptM]MaxPlot,\[ScriptM]MaxMaxPlot}={4,10} \[ScriptM]E;\[ScriptC]MaxPlot=cE[\[ScriptM]MaxPlot];
Manipulate[Block[{$PerformanceGoal="Quality",r, \[Mho], \[CurlyTheta], \[Rho], \[GothicG],\[CurlyTheta]Base,\[GothicG]Base,\[Rho]Base,\[Mho]Base,rBase},
r=rBase=p1;\[Mho]=\[Mho]Base= p2/100;\[CurlyTheta]=\[CurlyTheta]Base=p3;\[Rho]=\[Rho]Base=p4;\[GothicG]=\[GothicG]Base=p5;If[\[CapitalThorn]Rtn> 1||\[CapitalThorn]\[CapitalGamma] > 1
,(* then *)
If[\[CapitalThorn]Rtn> 1
,(* then *) Style[Text["RIC Fails."],24]
,(* else *) Style[Text["GIC Fails."],24]]
,(* else *)
\[ScriptM]TargetDiagram[\[ScriptM]MaxPlot,\[ScriptM]MaxMaxPlot,\[ScriptC]MaxPlot]]
]
,{{p1,0.05,"r"},0.05-.02,0.05+.02,Appearance->"Labeled"}
,{{p2,1,"\[Mho]Times100"},1-0.99,1+2,Appearance->"Labeled"}
,{{p3,.10,"\[CurlyTheta]"},.10-.05,.10+.05,Appearance->"Labeled"}
,{{p4,3,"\[Rho]"},2,4,Appearance->"Labeled"}
,{{p5,0.02,"\[GothicG]"},0.02-.02,0.02+.02,Appearance->"Labeled"}
]
